In [3]:
#pip install pandas

In [4]:
import pandas as p

In [5]:
a=[10,20,30,40,50,62,78]
p.Series(a)

0    10
1    20
2    30
3    40
4    50
5    62
6    78
dtype: int64

In [7]:
b=[2.3,60.2,5.1,8.6]
p.Series(b)

0     2.3
1    60.2
2     5.1
3     8.6
dtype: float64

In [8]:
c=['name','gayathri','kalyani','satyanarayana']
p.Series(c)

0             name
1         gayathri
2          kalyani
3    satyanarayana
dtype: str

In [10]:
d=[True,False]
p.Series(d)

0     True
1    False
dtype: bool

In [12]:
e=[5-10j,6+30j]
p.Series(e)

0    5.0-10.0j
1    6.0+30.0j
dtype: complex128

In [15]:
data={'names':['kusuma','dhatri','haranatha'],'marks':[90,60,80]}
p.DataFrame(data)

       names  marks
0     kusuma     90
1     dhatri     60
2  haranatha     80

In [18]:
dat={'names':['kusuma','dhatri','haranatha'], 'subjects':['maths','science','social'],'marks':[90,95,80],'percentages':[98,98,97]}
p.DataFrame(dat)

       names subjects  marks  percentages
0     kusuma    maths     90           98
1     dhatri  science     95           98
2  haranatha   social     80           97